### ISSUE TITLE
Flatpak 

### ISSUE THREAD

**Issue by Mars7x** [wheremyfoodat/Panda3DS#108]
Having a Flatpak build would be nice for Linux, especially since almost all modern emulators support it.

Benefits of Flatpak:

- The user doesn't need to worry about dependencies.
- Easy to install and uninstall.
- Universal format.
- Sandboxed/isolated from your system, so your install won't break as easily.
- Easier to solve issues because every Flatpak install will be identical.

**Comment by wheremyfoodat** [comment]
Personally I've been thinking of shipping builds via AppImage like we do with Redux and also set up an AUR package. 

Need to compare AppImage vs Flatpak better to see which one's preferable.

**Comment by Mars7x** [comment]
AppImage would also be cool and is probably easier than making a Flatpak.

Only issue I have with it is that it doesn't really integrate with your system and you can't update the app from your software manager, but it's not that big of a deal.

**Comment by ultimaweapon** [comment]
With AppImage the application will look for any missing dependencies from the system so it have more chance to have dependency problems than Flatpak.

**Comment by wheremyfoodat** [comment]
> With AppImage the application will look for any missing dependencies from the system so it have more chance to have dependency problems than Flatpak.

Doesn't really matter. There's noy really any system dependencies aside from the ones SDL2 brings in (which is mostly Xlib stuff that any Linux PC has)

**Comment by wheremyfoodat** [comment]
AppImage support added in #259 and AUR support added in #229, hopefully should mitigate most Linux distribution problems

**Comment by JakobDev** [comment]
I could help you with a Flatpak, if you are interested

**Comment by wheremyfoodat** [comment]
> I could help you with a Flatpak, if you are interested

That would be nice for people that can't use AppImage if it's not too much of a trouble. Even moreso if it's feasible to get the package on flathub.

**Comment by JakobDev** [comment]
I have craeted a Mainfest shich build from main:
```yaml
id: com.panda3ds.Panda3DS
runtime: org.kde.Platform
runtime-version: "6.6"
sdk: org.kde.Sdk
finish-args:
  - --socket=fallback-x11
  - --socket=wayland
  - --device=all
  - --share=ipc

modules:
  - name: Panda3DS
    buildsystem: cmake-ninja
    config-opts:
      - -DENABLE_USER_BUILD=true
      - -DENABLE_QT_GUI=true
    sources:
      - type: git
        url: https://github.com/wheremyfoodat/Panda3DS.git
```
The build fails with
```
-- Found WrapVulkanHeaders: /usr/include  
CMake Error at third_party/SDL2/CMakeLists.txt:2 (message):
  Prevented in-tree build.  Please create a build directory outside of the
  SDL source code and run "cmake -S /run/build/Panda3DS -B ." from there
```
You don't need to build SDL2. It is already included in the Runtime.

**Comment by wheremyfoodat** [comment]
Is there a way to configure which directory the code is built from? Normally if you do `mkdir build && cd build && cmake .. <stuff>` like CI does, this shouldn't happen

**Comment by JakobDev** [comment]
I got the build to work now. The Emulator starts, but when trying to open Rom, it just prints `OpenFile failed` in the console and does nothing.

This is my current Manifest:
```yaml
id: com.panda3ds.Panda3DS
runtime: org.kde.Platform
runtime-version: "6.6"
sdk: org.kde.Sdk
command: Alber
finish-args:
  - --socket=fallback-x11
  - --socket=wayland
  - --device=all
  - --share=ipc

modules:
  - name: Panda3DS
    buildsystem: cmake-ninja
    builddir: true
    config-opts:
      - -DENABLE_USER_BUILD=true
      - -DENABLE_QT_GUI=true
      - -DENABLE_DISCORD_RPC=false
    post-install:
      - install -Dm755 Alber -t $FLATPAK_DEST/bin
      - install -Dm644 ../docs/img/Alber.png  $FLATPAK_DEST/share/icons/hicolor/512x512/apps/$FLATPAK_ID.png
      - install -Dm644 ../.github/Alber.desktop $FLATPAK_DEST/share/applications/$FLATPAK_ID.desktop
      - desktop-file-edit --set-icon=$FLATPAK_ID $FLATPAK_DEST/share/applications/$FLATPAK_ID.desktop
    sources:
      - type: git
        url: https://github.com/wheremyfoodat/Panda3DS.git
```
